version: '3.6'

services:
  react:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - './:/app'
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
      - "35729:35729"
